name: Documenter

on:
  push:
    branches: main
    tags: '*'
  pull_request:
  merge_group:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Documenter:
    uses: EpiAware/.github/.github/workflows/documentation.yml@42a0501ccacefbfc2f2eeca640714a19c50bfe58
    secrets: inherit  # pragma: allowlist secret
