name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    uses: EpiAware/.github/.github/workflows/format-check.yml@42a0501ccacefbfc2f2eeca640714a19c50bfe58
    secrets: inherit  # pragma: allowlist secret
